import { User, Institute, Complaint, Notification, AuditLog } from './types';

export const mockUsers: User[] = [
  {
    id: '1',
    email: 'student@example.com',
    name: 'Priya Sharma',
    role: 'student',
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    email: 'admin@sjc.edu',
    name: 'Dr. Rajesh Kumar',
    role: 'institute_admin',
    instituteId: 'inst-1',
    createdAt: '2023-06-10T08:00:00Z',
  },
  {
    id: '3',
    email: 'official@gov.in',
    name: 'Mrs. Anita Desai',
    role: 'government_official',
    districtId: 'dist-1',
    createdAt: '2023-03-20T09:00:00Z',
  },
  {
    id: '4',
    email: 'admin@eduwatch.gov',
    name: 'System Admin',
    role: 'platform_admin',
    createdAt: '2023-01-01T00:00:00Z',
  },
];

export const mockInstitutes: Institute[] = [
  {
    id: 'inst-1',
    name: 'St. Joseph\'s College',
    type: 'college',
    address: '123 MG Road, Bangalore',
    district: 'Bangalore Urban',
    state: 'Karnataka',
    verified: true,
    trustScore: 87,
    responseRate: 92,
    avgResolutionTime: 48,
    totalComplaints: 234,
    resolvedComplaints: 215,
    adminIds: ['2'],
    createdAt: '2020-01-01T00:00:00Z',
  },
  {
    id: 'inst-2',
    name: 'Government High School, Whitefield',
    type: 'school',
    address: 'Whitefield Main Road, Bangalore',
    district: 'Bangalore Urban',
    state: 'Karnataka',
    verified: true,
    trustScore: 72,
    responseRate: 78,
    avgResolutionTime: 96,
    totalComplaints: 156,
    resolvedComplaints: 122,
    adminIds: [],
    createdAt: '2019-06-15T00:00:00Z',
  },
  {
    id: 'inst-3',
    name: 'National Institute of Technology',
    type: 'university',
    address: 'NIT Campus, Surathkal',
    district: 'Dakshina Kannada',
    state: 'Karnataka',
    verified: true,
    trustScore: 94,
    responseRate: 96,
    avgResolutionTime: 36,
    totalComplaints: 412,
    resolvedComplaints: 398,
    adminIds: [],
    createdAt: '2018-08-01T00:00:00Z',
  },
  {
    id: 'inst-4',
    name: 'Delhi Public School',
    type: 'school',
    address: 'Sector 45, Noida',
    district: 'Gautam Buddha Nagar',
    state: 'Uttar Pradesh',
    verified: true,
    trustScore: 89,
    responseRate: 91,
    avgResolutionTime: 52,
    totalComplaints: 189,
    resolvedComplaints: 172,
    adminIds: [],
    createdAt: '2019-01-10T00:00:00Z',
  },
  {
    id: 'inst-5',
    name: 'Mumbai University',
    type: 'university',
    address: 'Kalina Campus, Mumbai',
    district: 'Mumbai Suburban',
    state: 'Maharashtra',
    verified: true,
    trustScore: 81,
    responseRate: 85,
    avgResolutionTime: 72,
    totalComplaints: 678,
    resolvedComplaints: 576,
    adminIds: [],
    createdAt: '2018-03-15T00:00:00Z',
  },
];

export const mockComplaints: Complaint[] = [
  {
    id: 'comp-1',
    title: 'Broken water fountain in Block A',
    description: 'The water fountain on the 2nd floor of Block A has been broken for over a week. Students are struggling to access drinking water during hot days. The pipe is leaking and water is flooding the corridor.',
    category: 'infrastructure',
    urgency: 'high',
    status: 'in-progress',
    studentId: '1',
    studentName: 'Priya Sharma',
    isAnonymous: false,
    instituteId: 'inst-1',
    instituteName: 'St. Joseph\'s College',
    location: 'Block A, 2nd Floor',
    department: 'General',
    images: [],
    confirmations: 12,
    viewCount: 145,
    escalated: false,
    timeline: [
      {
        id: 'tl-1',
        complaintId: 'comp-1',
        type: 'status_change',
        title: 'Complaint Submitted',
        description: 'Complaint submitted by student',
        actor: 'Priya Sharma',
        actorRole: 'student',
        createdAt: '2024-05-10T09:30:00Z',
      },
      {
        id: 'tl-2',
        complaintId: 'comp-1',
        type: 'status_change',
        title: 'Under Review',
        description: 'Institute has acknowledged the complaint',
        actor: 'Dr. Rajesh Kumar',
        actorRole: 'institute_admin',
        createdAt: '2024-05-10T14:20:00Z',
      },
      {
        id: 'tl-3',
        complaintId: 'comp-1',
        type: 'status_change',
        title: 'In Progress',
        description: 'Maintenance team has been assigned',
        actor: 'Dr. Rajesh Kumar',
        actorRole: 'institute_admin',
        createdAt: '2024-05-12T10:00:00Z',
      },
    ],
    comments: [
      {
        id: 'cm-1',
        complaintId: 'comp-1',
        userId: '2',
        userName: 'Dr. Rajesh Kumar',
        userRole: 'institute_admin',
        content: 'We have assigned our maintenance team to fix this issue. Expected resolution by end of week.',
        isOfficial: true,
        createdAt: '2024-05-10T14:30:00Z',
      },
    ],
    instituteResponse: {
      message: 'Thank you for reporting this issue. Our maintenance team is working on it and we expect to have it fixed by May 15th.',
      status: 'in-progress',
      respondedBy: 'Dr. Rajesh Kumar',
      respondedAt: '2024-05-10T14:20:00Z',
    },
    aiAnalysis: {
      confidence: 92,
      category: 'infrastructure',
      urgency: 'high',
      sentiment: 'negative',
      keywords: ['water', 'fountain', 'broken', 'leaking', 'flooding'],
      flagged: false,
      analyzedAt: '2024-05-10T09:31:00Z',
    },
    createdAt: '2024-05-10T09:30:00Z',
    updatedAt: '2024-05-12T10:00:00Z',
  },
  {
    id: 'comp-2',
    title: 'Unclean washrooms in girls hostel',
    description: 'The washrooms in the girls hostel have not been cleaned properly for the past 3 days. There is a foul smell and unhygienic conditions. This is affecting the health and well-being of students.',
    category: 'hygiene',
    urgency: 'critical',
    status: 'resolved',
    studentId: '1',
    isAnonymous: true,
    instituteId: 'inst-1',
    instituteName: 'St. Joseph\'s College',
    location: 'Girls Hostel, Block C',
    images: [],
    confirmations: 8,
    viewCount: 98,
    escalated: false,
    timeline: [
      {
        id: 'tl-4',
        complaintId: 'comp-2',
        type: 'status_change',
        title: 'Complaint Submitted',
        description: 'Anonymous complaint submitted',
        actor: 'Anonymous',
        actorRole: 'student',
        createdAt: '2024-05-08T08:00:00Z',
      },
      {
        id: 'tl-5',
        complaintId: 'comp-2',
        type: 'status_change',
        title: 'Resolved',
        description: 'Issue has been resolved',
        actor: 'Dr. Rajesh Kumar',
        actorRole: 'institute_admin',
        createdAt: '2024-05-09T16:00:00Z',
      },
    ],
    comments: [],
    instituteResponse: {
      message: 'We have immediately addressed this issue. Additional housekeeping staff has been assigned and a deep cleaning has been completed.',
      status: 'resolved',
      respondedBy: 'Dr. Rajesh Kumar',
      respondedAt: '2024-05-09T16:00:00Z',
    },
    aiAnalysis: {
      confidence: 95,
      category: 'hygiene',
      urgency: 'critical',
      sentiment: 'negative',
      keywords: ['washrooms', 'unclean', 'smell', 'unhygienic', 'health'],
      flagged: false,
      analyzedAt: '2024-05-08T08:01:00Z',
    },
    createdAt: '2024-05-08T08:00:00Z',
    updatedAt: '2024-05-09T16:00:00Z',
    resolvedAt: '2024-05-09T16:00:00Z',
  },
  {
    id: 'comp-3',
    title: 'Inadequate library resources for Computer Science',
    description: 'The library lacks updated Computer Science books and research journals. Most books are from 2015 or earlier, which don\'t cover modern technologies and frameworks.',
    category: 'academics',
    urgency: 'medium',
    status: 'under-review',
    studentId: '1',
    studentName: 'Priya Sharma',
    isAnonymous: false,
    instituteId: 'inst-1',
    instituteName: 'St. Joseph\'s College',
    location: 'Central Library',
    department: 'Computer Science',
    images: [],
    confirmations: 15,
    viewCount: 203,
    escalated: false,
    timeline: [
      {
        id: 'tl-6',
        complaintId: 'comp-3',
        type: 'status_change',
        title: 'Complaint Submitted',
        description: 'Complaint submitted by student',
        actor: 'Priya Sharma',
        actorRole: 'student',
        createdAt: '2024-05-05T11:00:00Z',
      },
      {
        id: 'tl-7',
        complaintId: 'comp-3',
        type: 'status_change',
        title: 'Under Review',
        description: 'Library committee is reviewing the request',
        actor: 'Dr. Rajesh Kumar',
        actorRole: 'institute_admin',
        createdAt: '2024-05-06T09:30:00Z',
      },
    ],
    comments: [
      {
        id: 'cm-2',
        complaintId: 'comp-3',
        userId: '2',
        userName: 'Dr. Rajesh Kumar',
        userRole: 'institute_admin',
        content: 'Thank you for bringing this to our attention. The library committee is reviewing the budget for new acquisitions.',
        isOfficial: true,
        createdAt: '2024-05-06T09:35:00Z',
      },
    ],
    aiAnalysis: {
      confidence: 88,
      category: 'academics',
      urgency: 'medium',
      sentiment: 'neutral',
      keywords: ['library', 'resources', 'books', 'outdated', 'computer science'],
      flagged: false,
      analyzedAt: '2024-05-05T11:01:00Z',
    },
    createdAt: '2024-05-05T11:00:00Z',
    updatedAt: '2024-05-06T09:30:00Z',
  },
  {
    id: 'comp-4',
    title: 'Poor lighting in parking area creates safety concerns',
    description: 'The parking area has very poor lighting, making it unsafe for students returning late from library or evening classes. There have been reports of suspicious activities.',
    category: 'safety',
    urgency: 'high',
    status: 'notified',
    studentId: '1',
    isAnonymous: true,
    instituteId: 'inst-2',
    instituteName: 'Government High School, Whitefield',
    location: 'Parking Area',
    images: [],
    confirmations: 22,
    viewCount: 312,
    escalated: true,
    escalatedAt: '2024-05-07T10:00:00Z',
    escalationReason: 'No response from institute within 48 hours for critical safety issue',
    timeline: [
      {
        id: 'tl-8',
        complaintId: 'comp-4',
        type: 'status_change',
        title: 'Complaint Submitted',
        description: 'Anonymous complaint submitted',
        actor: 'Anonymous',
        actorRole: 'student',
        createdAt: '2024-05-05T18:30:00Z',
      },
      {
        id: 'tl-9',
        complaintId: 'comp-4',
        type: 'escalation',
        title: 'Escalated to District Education Officer',
        description: 'Escalated due to no response within SLA',
        actor: 'System',
        actorRole: 'platform_admin',
        createdAt: '2024-05-07T10:00:00Z',
      },
    ],
    comments: [],
    aiAnalysis: {
      confidence: 94,
      category: 'safety',
      urgency: 'high',
      sentiment: 'negative',
      keywords: ['lighting', 'parking', 'unsafe', 'security', 'suspicious'],
      flagged: true,
      flagReason: 'Safety concern requiring immediate attention',
      analyzedAt: '2024-05-05T18:31:00Z',
    },
    createdAt: '2024-05-05T18:30:00Z',
    updatedAt: '2024-05-07T10:00:00Z',
  },
  {
    id: 'comp-5',
    title: 'Exam hall ceiling fan not working',
    description: 'One of the ceiling fans in Exam Hall B is not working. With summer exams ongoing, it\'s becoming very difficult for students to concentrate.',
    category: 'infrastructure',
    urgency: 'medium',
    status: 'resolved',
    studentId: '1',
    studentName: 'Priya Sharma',
    isAnonymous: false,
    instituteId: 'inst-1',
    instituteName: 'St. Joseph\'s College',
    location: 'Exam Hall B',
    images: [],
    confirmations: 6,
    viewCount: 78,
    escalated: false,
    timeline: [
      {
        id: 'tl-10',
        complaintId: 'comp-5',
        type: 'status_change',
        title: 'Complaint Submitted',
        description: 'Complaint submitted by student',
        actor: 'Priya Sharma',
        actorRole: 'student',
        createdAt: '2024-05-03T10:00:00Z',
      },
      {
        id: 'tl-11',
        complaintId: 'comp-5',
        type: 'status_change',
        title: 'Resolved',
        description: 'Fan has been repaired',
        actor: 'Dr. Rajesh Kumar',
        actorRole: 'institute_admin',
        createdAt: '2024-05-03T15:00:00Z',
      },
    ],
    comments: [],
    instituteResponse: {
      message: 'The fan has been repaired immediately. Thank you for reporting.',
      status: 'resolved',
      respondedBy: 'Dr. Rajesh Kumar',
      respondedAt: '2024-05-03T15:00:00Z',
    },
    aiAnalysis: {
      confidence: 90,
      category: 'infrastructure',
      urgency: 'medium',
      sentiment: 'neutral',
      keywords: ['ceiling', 'fan', 'exam', 'hall', 'not working'],
      flagged: false,
      analyzedAt: '2024-05-03T10:01:00Z',
    },
    createdAt: '2024-05-03T10:00:00Z',
    updatedAt: '2024-05-03T15:00:00Z',
    resolvedAt: '2024-05-03T15:00:00Z',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    userId: '1',
    type: 'status_update',
    title: 'Your complaint is now in progress',
    message: 'The institute has started working on your complaint about the broken water fountain.',
    link: '/dashboard/reports/comp-1',
    read: false,
    createdAt: '2024-05-12T10:00:00Z',
  },
  {
    id: 'notif-2',
    userId: '1',
    type: 'response',
    title: 'Institute responded to your complaint',
    message: 'Dr. Rajesh Kumar has posted a response to your complaint.',
    link: '/dashboard/reports/comp-1',
    read: false,
    createdAt: '2024-05-10T14:30:00Z',
  },
  {
    id: 'notif-3',
    userId: '1',
    type: 'status_update',
    title: 'Complaint resolved',
    message: 'Your complaint about washroom cleanliness has been marked as resolved.',
    link: '/dashboard/reports/comp-2',
    read: true,
    createdAt: '2024-05-09T16:00:00Z',
  },
  {
    id: 'notif-4',
    userId: '1',
    type: 'confirmation',
    title: '12 students confirmed your complaint',
    message: 'Your complaint about the water fountain has been confirmed by 12 other students.',
    link: '/dashboard/reports/comp-1',
    read: true,
    createdAt: '2024-05-11T12:00:00Z',
  },
];

export const mockAuditLogs: AuditLog[] = [
  {
    id: 'audit-1',
    userId: '2',
    userName: 'Dr. Rajesh Kumar',
    userRole: 'institute_admin',
    action: 'Updated complaint status',
    resource: 'complaint',
    resourceId: 'comp-1',
    details: 'Changed status from "under-review" to "in-progress"',
    createdAt: '2024-05-12T10:00:00Z',
  },
  {
    id: 'audit-2',
    userId: '1',
    userName: 'Priya Sharma',
    userRole: 'student',
    action: 'Created complaint',
    resource: 'complaint',
    resourceId: 'comp-1',
    details: 'New complaint: Broken water fountain in Block A',
    createdAt: '2024-05-10T09:30:00Z',
  },
  {
    id: 'audit-3',
    userId: '2',
    userName: 'Dr. Rajesh Kumar',
    userRole: 'institute_admin',
    action: 'Posted response',
    resource: 'complaint',
    resourceId: 'comp-1',
    details: 'Posted official response to complaint',
    createdAt: '2024-05-10T14:30:00Z',
  },
];
